name: Test
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  WORKSPACE_PATH: D:\workspace

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: "Run SDK Tests"
    runs-on: windows-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Setup Dev Drive and Checkout
        id: setup_dev_drive_checkout
        uses: videre-project/MTGOSDK/.github/actions/setup-dev-drive@main

      - name: Download MTGOSDK Feed
        uses: videre-project/MTGOSDK/.github/actions/download-artifact@main
        with:
          name: mtgosdk-feed
          path: ${{ env.WORKSPACE_PATH }}/packages
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET and Restore NuGet Packages
        uses: videre-project/MTGOSDK/.github/actions/setup-dotnet@main
        with:
          WORKSPACE_PATH: ${{ env.WORKSPACE_PATH }}

      # Create .env file for integration tests
      - name: Create .env file
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" > .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        shell: powershell
        working-directory: ${{ env.WORKSPACE_PATH }}

      # Run the test suite
      - name: Run tests
        run: dotnet test MTGOSDK.Tests -p:UseLocalFeed=true
        shell: powershell
        working-directory: ${{ env.WORKSPACE_PATH }}

      # Show the Diver logs for debugging test failures or crashes
      - if: ${{ failure() }}
        run: Get-Content $env:LOCALAPPDATA\MTGOSDK\Logs\* -Tail 1000
        shell: powershell
